In [1]:
import pandas as pd
import numpy as np
import pyarrow.parquet as pq


def load_df(path, columns=None, nthreads=4, strings_to_categorical=True):
    try:
        table = pq.read_table(path, columns=columns, nthreads=nthreads)
        return table.to_pandas(strings_to_categorical=strings_to_categorical)
    except Exception as e:
        print(e)


cols = ['device_id', 'timestamp', 'battery_state', 'battery_level']
        
df = load_df('../src/samples.parquet', cols).sort_values(by=['device_id', 'timestamp'])

df = df.reset_index(drop=True)

df_int = df.select_dtypes(include=['int'])
converted_int = df_int.apply(pd.to_numeric, downcast='unsigned')

df[converted_int.columns] = converted_int

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2854918 entries, 0 to 2854917
Data columns (total 4 columns):
device_id        uint16
timestamp        datetime64[ns]
battery_state    category
battery_level    int8
dtypes: category(1), datetime64[ns](1), int8(1), uint16(1)
memory usage: 32.7 MB

In [2]:
# additional features
df['time_diff'] = df['timestamp'].diff()
df.loc[df.device_id != df.device_id.shift(), 'time_diff'] = None

In [4]:
df[df.device_id == 2330].head(50)

         device_id           timestamp battery_state  battery_level time_diff
2113676       2330 2017-11-01 00:39:27   discharging             97       NaT
2113677       2330 2017-11-01 01:45:16   discharging             96  01:05:49
2113678       2330 2017-11-01 02:41:14   discharging             95  00:55:58
2113679       2330 2017-11-01 04:13:24   discharging             94  01:32:10
2113680       2330 2017-11-01 05:51:28   discharging             93  01:38:04
2113681       2330 2017-11-01 07:15:24   discharging             92  01:23:56
2113682       2330 2017-11-01 08:13:33   discharging             91  00:58:09
2113683       2330 2017-11-01 08:52:37   discharging             90  00:39:04
2113684       2330 2017-11-01 09:21:18   discharging             89  00:28:41
2113685       2330 2017-11-01 10:16:56   discharging             88  00:55:38
2113686       2330 2017-11-01 10:49:57   discharging             87  00:33:01
2113687       2330 2017-11-01 12:47:38   discharging             86  01:57:41
2113688       2330 2017-11-01 14:46:23   discharging             85  01:58:45
2113689       2330 2017-11-01 16:32:38   discharging             84  01:46:15
2113690       2330 2017-11-01 16:57:37   discharging             83  00:24:59
2113691       2330 2017-11-01 18:03:59   discharging             82  01:06:22
2113692       2330 2017-11-01 18:04:29   discharging             82  00:00:30
2113693       2330 2017-11-01 18:23:09   discharging             81  00:18:40
2113694       2330 2017-11-01 18:45:21   discharging             80  00:22:12
2113695       2330 2017-11-01 19:22:37   discharging             79  00:37:16
2113696       2330 2017-11-01 21:25:00   discharging             78  02:02:23
2113697       2330 2017-11-02 09:54:18   discharging             63  12:29:18
2113698       2330 2017-11-02 12:00:37   discharging             60  02:06:19
2113699       2330 2017-11-02 17:32:52   discharging             51  05:32:15
2113700       2330 2017-11-02 17:36:11      charging             52  00:03:19
2113701       2330 2017-11-02 17:38:32      charging             53  00:02:21
2113702       2330 2017-11-02 17:40:53      charging             54  00:02:21
2113703       2330 2017-11-02 17:43:04      charging             55  00:02:11
2113704       2330 2017-11-02 17:45:14      charging             56  00:02:10
2113705       2330 2017-11-02 17:47:15      charging             56  00:02:01
2113706       2330 2017-11-02 17:49:36      charging             57  00:02:21
2113707       2330 2017-11-02 17:51:47      charging             59  00:02:11
2113708       2330 2017-11-02 17:53:48      charging             60  00:02:01
2113709       2330 2017-11-02 17:55:58      charging             61  00:02:10
2113710       2330 2017-11-02 17:58:19      charging             62  00:02:21
2113711       2330 2017-11-02 18:00:30      charging             63  00:02:11
2113712       2330 2017-11-02 18:02:31      charging             64  00:02:01
2113713       2330 2017-11-02 18:04:52      charging             65  00:02:21
2113714       2330 2017-11-02 18:07:12      charging             66  00:02:20
2113715       2330 2017-11-02 18:09:33      charging             67  00:02:21
2113716       2330 2017-11-02 18:11:54      charging             68  00:02:21
2113717       2330 2017-11-02 18:14:05      charging             69  00:02:11
2113718       2330 2017-11-02 18:15:35      charging             70  00:01:30
2113719       2330 2017-11-02 18:16:36      charging             71  00:01:01
2113720       2330 2017-11-02 18:18:36      charging             72  00:02:00
2113721       2330 2017-11-02 18:21:44   discharging             71  00:03:08
2113722       2330 2017-11-02 18:24:14   discharging             70  00:02:30
2113723       2330 2017-11-02 18:26:45   discharging             69  00:02:31
2113724       2330 2017-11-02 18:29:15   discharging             68  00:02:30
2113725       2330 2017-11-02 18:32:15   discharging             67  00:03:00