In [1]:
import pandas as pd
import numpy as np

samples_data = pd.read_csv('C:\\Users\\ruben\\Desktop\\Investigation\\updated_dataset_07_3_2018\\samples.csv', usecols=['device_id', 'bluetooth_enabled', 'location_enabled', 'power_saver_enabled', 'flashlight_enabled', 'nfc_enabled', 'unknown_sources', 'developer_mode'])

samples_data.head()

,device_id,bluetooth_enabled,location_enabled,power_saver_enabled,flashlight_enabled,nfc_enabled,unknown_sources,developer_mode
0,1,0,1,0,0,0,0,0
1,1,0,1,0,0,0,0,0
2,1,0,1,0,0,0,0,0
3,1,0,1,0,0,0,0,0
4,1,0,1,0,0,0,0,0

In [9]:
services_table = samples_data.groupby(samples_data.columns.tolist()).size().reset_index().rename(columns={0:'count'})

print(len(samples_data))
print(len(services_table))
print(len(services_table)/len(samples_data) * 100)
services_table

4036846
5704
0.14129842951650867

,device_id,bluetooth_enabled,location_enabled,power_saver_enabled,flashlight_enabled,nfc_enabled,unknown_sources,developer_mode,count
0,1,0,0,0,0,0,0,0,19
1,1,0,1,0,0,0,0,0,4051
2,1,0,1,1,0,0,0,0,56
3,1,1,1,0,0,0,0,0,1088
4,1,1,1,1,0,0,0,0,29
5,3,0,1,0,0,0,1,1,68
6,4,0,0,0,0,1,1,0,128
7,4,0,0,0,0,1,1,1,971
8,4,0,1,0,0,0,1,1,4
9,4,0,1,0,0,1,1,1,7814
10,5,0,1,0,0,0,0,0,66
11,6,0,0,0,0,1,1,0,1245
12,6,0,1,0,0,0,1,0,36
13,6,0,1,0,0,1,1,0,8197
14,6,1,1,0,0,1,1,0,12988
15,8,0,0,0,0,0,0,0,1
16,9,0,0,0,0,0,0,1,218
17,9,0,0,1,0,0,0,1,4
18,10,0,1,0,0,0,0,0,3652
19,12,0,1,0,0,0,0,0,1933
20,12,1,0,0,0,0,0,0,2
21,12,1,1,0,0,0,0,0,23678
22,14,0,0,0,0,0,0,0,31
23,15,1,1,0,0,0,1,1,1
24,16,0,1,0,0,0,0,0,6701
25,16,0,1,1,0,0,0,0,2362
26,16,1,1,0,0,0,0,0,7
27,16,1,1,1,0,0,0,0,2
28,19,0,0,0,0,0,0,0,32
29,19,0,1,0,0,0,0,0,17
...,...,...,...,...,...,...,...,...,...
5674,3085,0,0,0,0,0,1,0,1
5675,3086,0,0,0,0,0,1,0,4
5676,3087,0,0,0,0,0,1,0,1004
5677,3088,0,0,0,0,1,0,0,97
5678,3089,0,0,0,0,0,1,0,2331
5679,3090,0,0,0,0,0,0,1,1
5680,3090,0,0,0,0,0,1,0,2
5681,3094,0,0,1,0,0,0,0,824
5682,3094,0,1,1,0,0,0,0,1
5683,3095,0,0,0,0,0,1,0,185
5684,3095,0,1,0,0,0,1,0,7
5685,3095,1,0,0,0,0,1,0,2
5686,3096,0,1,0,0,0,0,0,7
5687,3099,0,0,0,0,0,1,0,1
5688,3101,0,0,0,0,0,1,0,247
5689,3101,0,1,0,0,0,1,0,94
5690,3102,0,1,0,0,0,1,0,1
5691,3103,0,0,0,0,0,1,0,1
5692,3103,1,0,0,0,0,1,0,2
5693,3104,0,0,0,0,0,1,0,313
5694,3104,0,0,1,0,0,1,0,338
5695,3105,0,0,0,0,0,1,0,1
5696,3107,0,1,0,0,0,1,1,40
5697,3109,0,0,0,0,0,1,1,58
5698,3110,0,0,0,0,0,0,0,146
5699,3110,0,0,1,0,0,0,0,2
5700,3111,0,0,0,0,1,1,0,1
5701,3112,0,0,0,0,0,1,1,533
5702,3116,0,1,0,0,1,0,0,104
5703,3116,1,1,0,0,1,0,0,125

In [10]:
# services_table.to_csv('C:\\Users\\ruben\\Desktop\\services.csv', index=False, encoding='utf-8')

In [12]:
# def create_services_table(main_file_path, save_to_path):
#     samples_data = pd.read_csv(main_file_path, usecols=['device_id', 'bluetooth_enabled', 'location_enabled', 'power_saver_enabled', 'flashlight_enabled', 'nfc_enabled', 'unknown_sources', 'developer_mode'])
#     services_table = samples_data.groupby(samples_data.columns.tolist()).size().reset_index().rename(columns={0:'count'})
#     services_table.to_csv(save_to_path)

ok

['device_id',
 'bluetooth_enabled',
 'location_enabled',
 'power_saver_enabled',
 'flashlight_enabled',
 'nfc_enabled',
 'unknown_sources',
 'developer_mode']